specVersion: 1.0.0
name: gafi-query
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: ^0.33.0
  query:
    name: '@subql/query'
    version: 0.24.0
description: SubQuery project for GAFI network
repository: 'https://github.com/cryptoviet/gafi-query'
schema:
  file: ./schema.graphql
network:
  # endpoint: 'wss://ws.gafi.network'
  # genesisHash: '0x09e7f84fb89d0525b0ec0030922a67446555769be3dfe05396644653990a5e00'

  # Local env
  endpoint: 'ws://host.docker.internal:9944'
  genesisHash: '0x75d17a42971e5e93c6ea9712f3c8e70eaebf09a2e973b8218e3c9fbd9743b936'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleCall
          kind: substrate/CallHandler
        - handler: handleCreateSponsoredPool
          kind: substrate/EventHandler
          filter:
            module: sponsoredPool
            method: CreatedPool
        - handler: handleUserJoinPool
          kind: substrate/EventHandler
          filter:
            module: pool
            method: Joined
