specVersion: 1.0.0
name: gafi-query
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: ^0.33.0
  query:
    name: '@subql/query'
    version: 0.24.0
description: SubQuery project for GAFI network
repository: 'https://github.com/cryptoviet/gafi-query'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://ws.gafi.network'
  genesisHash: '0xe77952d987927d9431ebb6b32484cb219cb9dbafe902daccc81991cd2e1f285e'

  # Local env
  # endpoint: 'ws://host.docker.internal:9944'
  # genesisHash: '0x51e2ffe91ee57f283040ee7ffee9085d34ec61f53844b9b951f2c02e8c89e3f4'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleCall
          kind: substrate/CallHandler
        - handler: handleCreateSponsoredPool
          kind: substrate/EventHandler
          filter:
            module: sponsoredPool
            method: CreatedPool
        - handler: handleUserJoinPool
          kind: substrate/EventHandler
          filter:
            module: pool
            method: Joined
        - handler: handleClaimContract
          kind: substrate/EventHandler
          filter:
            module: gameCreator
            method: Claimed
        - handler: handleSponsoredPoolNewTargets
          kind: substrate/CallHandler
          filter:
            module: sponsoredPool
            method: newTargets
        - handler: handleSponsoredPoolWithdraw
          kind: substrate/CallHandler
          filter:
            module: sponsoredPool
            method: withdrawPool
